### ISSUE TITLE
Removing Arc from LC String

### ISSUE THREAD

**Issue by rondDev** [elijahimmer/wlrs-bar#2]
Am I missing something when it comes to the Arc around the LC string? It seems to be functioning fine without the Arc, perhaps there is something that I haven't noticed yet, if so, please enlighten me.

https://github.com/rondDev/wlrs-bar/blob/16cec469acdd55f48bd5cd373babf485fcdd5565/src/log.rs#L6

**Comment by elijahimmer** [comment]
At one point I was sharing the Log Contexts across threads, but now they are just copied around with child names instead. I fixed it in 7bc5736b90d9fb96fb995df0ca7a414ca5dac823
